### ISSUE TITLE
mxnet

### ISSUE THREAD

**Issue by sunrongda** [cypw/MXNet2Caffe#9]
Traceback (most recent call last):
  File "json2prototxt.py", line 38, in <module>
    write_node(prototxt_file, info)
  File "/root/MXNet2Caffe/prototxt_basic.py", line 143, in write_node
    Convolution(txt_file, info)
  File "/root/MXNet2Caffe/prototxt_basic.py", line 16, in Convolution
    if info['param']['no_bias'] == 'True':
KeyError: 'param'

**Comment by Tez01** [comment]
In prototxt_basic.py
I think the key should be params.
When I print info.keys() output is :
[u'inputs', u'name', 'bottom', 'top', 'params', u'attrs', u'op']
